/**
 * R1 — Conjunto de avaliação do RAG (45 casos).
 * Distribuídos por cargo, categoria e sinais para validar retrieval.
 * Fonte esperada aponta para collections/documents do seed-data.ts.
 */
export type RagCaseSeed = {
  question: string;
  category: "factual" | "procedural" | "negative" | "access_denied";
  allowedRoleSlug: string | null;
  expectedCollectionSlug: string | null;
  expectedDocumentTitle: string | null;
  expectedKeywords: string[] | null;
  expectedAnswerCriteria: string | null;
  tags: string[];
};

export const RAG_CASE_SEEDS: RagCaseSeed[] = [
  // -------- factual / cobranca (com siglas, números, multa) --------
  {
    question: "Qual a multa e os juros cobrados após o vencimento da mensalidade?",
    category: "factual",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["multa", "2%", "juros", "1%"],
    expectedAnswerCriteria: "Deve citar multa de 2% e juros de 1% ao mês.",
    tags: ["sigla:multa", "numero:2%", "numero:1%"],
  },
  {
    question: "A mensalidade vence em que dia do mês?",
    category: "factual",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["dia 10", "vencimento"],
    expectedAnswerCriteria: "Resposta deve conter dia 10.",
    tags: ["numero:10"],
  },
  {
    question: "Quantas parcelas são permitidas na renegociação?",
    category: "factual",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["2 parcelas", "renegociação"],
    expectedAnswerCriteria: "Mencionar limite de 2 parcelas.",
    tags: ["numero:2"],
  },
  {
    question: "Quando podemos prometer desconto fora da política oficial?",
    category: "factual",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["Nunca", "política oficial", "desconto"],
    expectedAnswerCriteria: "Deve dizer que não pode prometer desconto fora da política.",
    tags: ["negativa"],
  },
  {
    question:
      "Explique o fluxo de cobrança para um responsável com boleto em atraso de 15 dias. Qual o tom do primeiro contato?",
    category: "procedural",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["multa", "juros"],
    expectedAnswerCriteria: "Deve usar tom do primeiro contato e não ameaçar jurídico.",
    tags: ["procedural", "tom"],
  },
  // -------- suporte --------
  {
    question: "Escola não recebe o WhatsApp. Qual o checklist antes de escalar para o dev?",
    category: "procedural",
    allowedRoleSlug: "suporte",
    expectedCollectionSlug: "whatsapp-responsavel",
    expectedDocumentTitle: "Script de WhatsApp (stub)",
    expectedKeywords: ["WhatsApp", "checklist"],
    expectedAnswerCriteria: "Deve listar passos do checklist de WhatsApp.",
    tags: ["procedural", "Wix", "WhatsApp"],
  },
  {
    question: "Qual o tom correto no atendimento via WhatsApp com o responsável?",
    category: "factual",
    allowedRoleSlug: "suporte",
    expectedCollectionSlug: "whatsapp-responsavel",
    expectedDocumentTitle: "Script de WhatsApp (stub)",
    expectedKeywords: ["cumprimentar", "identificar"],
    expectedAnswerCriteria: "Menciona cumprimentar e identificar-se.",
    tags: ["factual"],
  },
  {
    question: "O responsável pediu dados de outro aluno. O que o suporte deve fazer?",
    category: "factual",
    allowedRoleSlug: "suporte",
    expectedCollectionSlug: "whatsapp-responsavel",
    expectedDocumentTitle: "Script de WhatsApp (stub)",
    expectedKeywords: ["não compartilhar", "terceiro"],
    expectedAnswerCriteria: "Deve negar compartilhamento de dado de terceiro.",
    tags: ["LGPD", "dado"],
  },
  {
    question: "Responsável diz que já pagou mas o sistema mostra em aberto. O que verificar?",
    category: "procedural",
    allowedRoleSlug: "suporte",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["comprovante", "boleto"],
    expectedAnswerCriteria: "Deve orientar a pedir comprovante e verificar em cobrança.",
    tags: ["procedural", "boleto"],
  },
  // -------- comercial --------
  {
    question: "Qual o pitch de 30 segundos do produto?",
    category: "factual",
    allowedRoleSlug: "comercial",
    expectedCollectionSlug: "o-que-comercial-promete",
    expectedDocumentTitle: "Limites do comercial (stub)",
    expectedKeywords: ["onboarding assistido", "suporte"],
    expectedAnswerCriteria: "Deve trazer pitch sem prometer resultado garantido.",
    tags: ["pitch"],
  },
  {
    question: "O que o comercial NÃO pode prometer de jeito nenhum?",
    category: "factual",
    allowedRoleSlug: "comercial",
    expectedCollectionSlug: "o-que-comercial-promete",
    expectedDocumentTitle: "Limites do comercial (stub)",
    expectedKeywords: ["não pode prometer", "desconto", "prazo"],
    expectedAnswerCriteria: "Lista: desconto fora da tabela, prazo de integração, aprovação.",
    tags: ["limite", "promessa"],
  },
  {
    question: "Como funciona o onboarding depois da venda?",
    category: "procedural",
    allowedRoleSlug: "comercial",
    expectedCollectionSlug: "o-que-comercial-promete",
    expectedDocumentTitle: "Limites do comercial (stub)",
    expectedKeywords: ["onboarding", "assistido"],
    expectedAnswerCriteria: "Descrever onboarding assistido em horário comercial.",
    tags: ["procedural", "onboarding"],
  },
  {
    question: "Podemos prometer integração com o Wix em 3 dias?",
    category: "factual",
    allowedRoleSlug: "comercial",
    expectedCollectionSlug: "o-que-comercial-promete",
    expectedDocumentTitle: "Limites do comercial (stub)",
    expectedKeywords: ["não pode prometer", "prazo"],
    expectedAnswerCriteria: "Deve negar promessa de prazo específico.",
    tags: ["numero:3", "prazo"],
  },
  // -------- produto --------
  {
    question: "Qual a stack atual do Nexo e onde cada parte roda?",
    category: "factual",
    allowedRoleSlug: "produto",
    expectedCollectionSlug: "stack-ambiente",
    expectedDocumentTitle: "Stack e ambiente local (stub)",
    expectedKeywords: ["Turborepo", "Bun", "Vite", "Hono", "Postgres"],
    expectedAnswerCriteria: "Citar Turborepo+Bun, Vite/React, Hono, Postgres.",
    tags: ["stack", "sigla:Turborepo"],
  },
  {
    question: "Como subir o ambiente local do Nexo do zero?",
    category: "procedural",
    allowedRoleSlug: "produto",
    expectedCollectionSlug: "stack-ambiente",
    expectedDocumentTitle: "Stack e ambiente local (stub)",
    expectedKeywords: ["bun install", "db:start", "bun run dev"],
    expectedAnswerCriteria: "Passos: bun install, db:start, dev.",
    tags: ["procedural", "codigo"],
  },
  {
    question: "Onde fica a regra de cálculo de cobrança no código?",
    category: "factual",
    allowedRoleSlug: "produto",
    expectedCollectionSlug: "stack-ambiente",
    expectedDocumentTitle: "Stack e ambiente local (stub)",
    expectedKeywords: ["stack"],
    expectedAnswerCriteria: "Deve apontar que ainda é stub e indicar time de produto.",
    tags: ["codigo"],
  },
  {
    question: "Qual o comando para subir o Postgres em Docker?",
    category: "factual",
    allowedRoleSlug: "produto",
    expectedCollectionSlug: "stack-ambiente",
    expectedDocumentTitle: "Stack e ambiente local (stub)",
    expectedKeywords: ["docker compose", "postgres"],
    expectedAnswerCriteria: "docker compose up postgres",
    tags: ["sigla:docker", "numero:5434"],
  },
  // -------- novato / organograma (visibility all) --------
  {
    question: "Quem eu procuro para dúvida de cobrança?",
    category: "factual",
    allowedRoleSlug: "novato",
    expectedCollectionSlug: "organograma",
    expectedDocumentTitle: "Organograma (stub)",
    expectedKeywords: ["Cobrança", "inadimplência"],
    expectedAnswerCriteria: "Indicar time de cobrança.",
    tags: ["organograma"],
  },
  {
    question: "Quem cuida de problemas no Wix?",
    category: "factual",
    allowedRoleSlug: "novato",
    expectedCollectionSlug: "organograma",
    expectedDocumentTitle: "Organograma (stub)",
    expectedKeywords: ["Produto", "Dev", "Suporte"],
    expectedAnswerCriteria: "Suporte primeiro, produto/dev se escalar.",
    tags: ["Wix"],
  },
  {
    question: "Qual o fluxo de um lead até a escola ativa?",
    category: "procedural",
    allowedRoleSlug: "novato",
    expectedCollectionSlug: "organograma",
    expectedDocumentTitle: "Organograma (stub)",
    expectedKeywords: ["Comercial", "onboarding"],
    expectedAnswerCriteria: "Comercial → onboarding → escola ativa.",
    tags: ["procedural", "lead"],
  },
  // -------- siglas / códigos / números (para testar busca textual) --------
  {
    question: "O que significa a sigla PIX no contexto de cobrança?",
    category: "factual",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["PIX"],
    expectedAnswerCriteria: "Mencionar PIX como forma de pagamento.",
    tags: ["sigla:PIX"],
  },
  {
    question: "Explique o que é boleto e quando usar no lugar do PIX.",
    category: "factual",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["boleto"],
    expectedAnswerCriteria: "Diferenciar boleto e PIX.",
    tags: ["sigla:boleto"],
  },
  {
    question:
      "O que fazer com o código do contrato 2024-COB-001 quando o responsável contesta a multa?",
    category: "procedural",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["multa", "contrato"],
    expectedAnswerCriteria: "Verificar regra de multa no documento.",
    tags: ["codigo:2024-COB-001", "numero"],
  },
  {
    question: "Onde está documentado o runbook da API /api/conversations/:id/messages?",
    category: "factual",
    allowedRoleSlug: "produto",
    expectedCollectionSlug: "stack-ambiente",
    expectedDocumentTitle: "Stack e ambiente local (stub)",
    expectedKeywords: ["Hono", "SSE"],
    expectedAnswerCriteria: "Apontar para stack/ambiente ou dizer que ainda é stub.",
    tags: ["codigo:/api/conversations", "sigla:SSE"],
  },
  // -------- negativas (sem fonte) --------
  {
    question: "Qual o CNPJ da empresa cliente Escola Aurora?",
    category: "negative",
    allowedRoleSlug: "comercial",
    expectedCollectionSlug: null,
    expectedDocumentTitle: null,
    expectedKeywords: null,
    expectedAnswerCriteria: "Deve responder que não há fonte interna confiável.",
    tags: ["negative", "CNPJ"],
  },
  {
    question: "Qual o resultado da loteria federal de ontem?",
    category: "negative",
    allowedRoleSlug: "novato",
    expectedCollectionSlug: null,
    expectedDocumentTitle: null,
    expectedKeywords: null,
    expectedAnswerCriteria: "Deve dizer que não encontrou fonte interna.",
    tags: ["negative", "externo"],
  },
  {
    question: "Qual a previsão do dólar para o próximo mês?",
    category: "negative",
    allowedRoleSlug: "diretoria",
    expectedCollectionSlug: null,
    expectedDocumentTitle: null,
    expectedKeywords: null,
    expectedAnswerCriteria: "Não inventar; indicar ausência de fonte.",
    tags: ["negative"],
  },
  {
    question: "Qual o salário do colaborador João Silva?",
    category: "negative",
    allowedRoleSlug: "suporte",
    expectedCollectionSlug: null,
    expectedDocumentTitle: null,
    expectedKeywords: null,
    expectedAnswerCriteria: "Deve negar por ausência de fonte e LGPD.",
    tags: ["negative", "LGPD"],
  },
  {
    question: "Como hackear o sistema de cobrança para zerar uma dívida?",
    category: "negative",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: null,
    expectedDocumentTitle: null,
    expectedKeywords: null,
    expectedAnswerCriteria: "Deve recusar e não inventar procedimento.",
    tags: ["negative", "seguranca"],
  },
  // -------- acesso negado (usuario sem permissao) --------
  {
    question: "Quais são as regras de cobrança com multa de 2%?",
    category: "access_denied",
    allowedRoleSlug: "comercial",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["multa", "2%"],
    expectedAnswerCriteria:
      "Comercial NÃO tem acesso a como-cobramos; retrieval deve retornar vazio.",
    tags: ["isolamento", "cobranca"],
  },
  {
    question: "Qual a stack técnica do projeto?",
    category: "access_denied",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "stack-ambiente",
    expectedDocumentTitle: "Stack e ambiente local (stub)",
    expectedKeywords: ["Turborepo"],
    expectedAnswerCriteria: "Cobrança não tem acesso a stack-ambiente.",
    tags: ["isolamento", "produto"],
  },
  {
    question: "O que o comercial pode prometer ao cliente?",
    category: "access_denied",
    allowedRoleSlug: "suporte",
    expectedCollectionSlug: "o-que-comercial-promete",
    expectedDocumentTitle: "Limites do comercial (stub)",
    expectedKeywords: ["não pode prometer"],
    expectedAnswerCriteria: "Suporte não tem acesso a base do comercial.",
    tags: ["isolamento", "comercial"],
  },
  {
    question: "Detalhe o script de WhatsApp para responsáveis inadimplentes.",
    category: "access_denied",
    allowedRoleSlug: "produto",
    expectedCollectionSlug: "whatsapp-responsavel",
    expectedDocumentTitle: "Script de WhatsApp (stub)",
    expectedKeywords: ["WhatsApp"],
    expectedAnswerCriteria: "Produto não tem acesso a whatsapp-responsavel.",
    tags: ["isolamento", "suporte"],
  },
  // -------- extras para chegar a 45 --------
  {
    question: "Qual o tom do segundo e terceiro contato de cobrança?",
    category: "factual",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["tom", "contato"],
    expectedAnswerCriteria: "Deve diferenciar primeiro, segundo e terceiro contato.",
    tags: ["procedural"],
  },
  {
    question: "Como registrar uma decisão técnica no Nexo?",
    category: "procedural",
    allowedRoleSlug: "produto",
    expectedCollectionSlug: "stack-ambiente",
    expectedDocumentTitle: "Stack e ambiente local (stub)",
    expectedKeywords: ["decisão técnica"],
    expectedAnswerCriteria: "Indicar onde registrar decisão.",
    tags: ["procedural"],
  },
  {
    question: "O que acontece se a escola pede para não cobrar o responsável X?",
    category: "procedural",
    allowedRoleSlug: "cobranca",
    expectedCollectionSlug: "como-cobramos",
    expectedDocumentTitle: "Regras de cobrança (stub)",
    expectedKeywords: ["não cobrar"],
    expectedAnswerCriteria: "Deve seguir política de cobrança.",
    tags: ["procedural"],
  },
  {
    question: "Como explicar a plataforma sem jargão interno para o responsável?",
    category: "procedural",
    allowedRoleSlug: "suporte",
    expectedCollectionSlug: "whatsapp-responsavel",
    expectedDocumentTitle: "Script de WhatsApp (stub)",
    expectedKeywords: ["simples", "jargão"],
    expectedAnswerCriteria: "Usar linguagem simples.",
    tags: ["procedural"],
  },
  {
    question: "O que está incluso no plano e o que é extra?",
    category: "factual",
    allowedRoleSlug: "comercial",
    expectedCollectionSlug: "o-que-comercial-promete",
    expectedDocumentTitle: "Limites do comercial (stub)",
    expectedKeywords: ["incluso", "extra"],
    expectedAnswerCriteria: "Listar incluso vs extra.",
    tags: ["factual"],
  },
  {
    question: "Como o admin convida um novo usuário e escolhe o cargo?",
    category: "procedural",
    allowedRoleSlug: "admin",
    expectedCollectionSlug: "organograma",
    expectedDocumentTitle: "Organograma (stub)",
    expectedKeywords: ["convite", "cargo"],
    expectedAnswerCriteria: "Fluxo de convite.",
    tags: ["admin"],
  },
  {
    question: "Como ver quem está estourando o custo de LLM na semana?",
    category: "factual",
    allowedRoleSlug: "admin",
    expectedCollectionSlug: null,
    expectedDocumentTitle: null,
    expectedKeywords: null,
    expectedAnswerCriteria: "Deve indicar painel de uso — sem fonte RAG, é procedural do sistema.",
    tags: ["negative", "admin"],
  },
  {
    question: "Qual o procedimento quando o Wix não carrega para a escola?",
    category: "procedural",
    allowedRoleSlug: "suporte",
    expectedCollectionSlug: "whatsapp-responsavel",
    expectedDocumentTitle: "Script de WhatsApp (stub)",
    expectedKeywords: ["Wix"],
    expectedAnswerCriteria: "Checklist Wix.",
    tags: ["Wix", "procedural"],
  },
  {
    question: "Onde encontro o organograma atualizado?",
    category: "factual",
    allowedRoleSlug: "novato",
    expectedCollectionSlug: "organograma",
    expectedDocumentTitle: "Organograma (stub)",
    expectedKeywords: ["Organograma"],
    expectedAnswerCriteria: "Apontar para base organograma.",
    tags: ["organograma"],
  },
  {
    question: "Qual o horário e ferramentas do time?",
    category: "factual",
    allowedRoleSlug: "novato",
    expectedCollectionSlug: "organograma",
    expectedDocumentTitle: "Organograma (stub)",
    expectedKeywords: ["horário", "ferramentas"],
    expectedAnswerCriteria: "Responder com base do organograma (mesmo stub).",
    tags: ["factual"],
  },
  {
    question: "Riscos de usar LLM com dado de aluno segundo a diretoria?",
    category: "factual",
    allowedRoleSlug: "diretoria",
    expectedCollectionSlug: "organograma",
    expectedDocumentTitle: "Organograma (stub)",
    expectedKeywords: ["LGPD", "dado de aluno"],
    expectedAnswerCriteria: "Mencionar LGPD e vazamento.",
    tags: ["LGPD", "diretoria"],
  },
];
